#######
# Compiled from data/turretz/functions/main.mcscript
# to .//data/turretz/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function turretz:arrow_turret/main
function turretz:fireball_turret/main
function turretz:wither_turret/main
execute as @a at @s run function turretz:creative_menu/main
execute as @a at @s if entity @e[tag=turretz_turret,distance=..5] run scoreboard players enable @s set_turret_mode
execute as @a at @s unless entity @e[tag=turretz_turret,distance=..5] if score @s set_turret_mode matches 0 run scoreboard players reset @s set_turret_mode
execute as @a at @s if score @s set_turret_mode matches 1..4 run function turretz:set_turret_mode