#######
# Compiled from data/turretz/functions/set_id.mcscript
# to .//data/turretz/functions/set_id.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation @s ud_owner_id = @p player_id