#######
# Compiled from data/turretz/functions/wither_turret.mcscript
# to .//data/turretz/functions/wither_turret/place_auto.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function turretz:wither_turret/place
kill @s[type=item]
