#######
# Compiled from data/turretz/functions/loot.mcscript
# to .//data/turretz/functions/loot/ghast.mcfunction
#
# Generated by Minecraft Script for 1.13
######
loot spawn ~ ~ ~ loot turretz:entities/ghast