#######
# Compiled from data/turretz/functions/loot.mcscript
# to .//data/turretz/functions/loot/wither_skeleton.mcfunction
#
# Generated by Minecraft Script for 1.13
######
loot spawn ~ ~ ~ loot turretz:entities/wither_skeleton
