#######
# Compiled from data/turretz/functions/loot.mcscript
# to .//data/turretz/functions/loot/wither.mcfunction
#
# Generated by Minecraft Script for 1.13
######
loot give @s loot turretz:entities/wither
