#######
# Compiled from data/turretz/functions/fireball_turret.mcscript
# to .//data/turretz/functions/fireball_turret/place_detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=item,nbt={Item:{tag:{turretz:{id:"ghast_ai"}}}}] at @s unless entity @e[type=armor_stand,tag=turretz_turret,distance=..1.5] if block ~ ~-1 ~ #minecraft:walls if block ~ ~-2 ~ #minecraft:walls if block ~ ~-3 ~ minecraft:dispenser[facing=up] run function turretz:fireball_turret/place_auto
