#######
# Compiled from data/turretz/functions/fireball_turret.mcscript
# to .//data/turretz/functions/fireball_turret/place_auto.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function turretz:fireball_turret/place
kill @s[type=item]
