#######
# Compiled from data/turretz/functions/fireball_turret.mcscript
# to .//data/turretz/functions/fireball_turret/shoot.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function turretz:fireball_turret/remove_fireball
scoreboard players set @s tur_cool 50
execute store result score @s x_pos run data get entity @s Pos[0] 100
execute store result score @s y_pos run data get entity @s Pos[1] 100
execute store result score @s z_pos run data get entity @s Pos[2] 100
summon area_effect_cloud ^ ^ ^2 {Tags:["turretz_dummy"]}
execute store result score @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] x_pos run data get entity @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] Pos[0] 100
execute store result score @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] y_pos run data get entity @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] Pos[1] 100
execute store result score @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] z_pos run data get entity @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] Pos[2] 100
scoreboard players operation @s x_pos -= @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] x_pos
scoreboard players operation @s y_pos -= @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] y_pos
scoreboard players operation @s z_pos -= @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] z_pos
summon fireball ^ ^ ^1 {Tags:["turretz_fireball"],ExplosionPower:0.75,direction:[0.0,0.0,0.0],power:[0.0,0.0,0.0]}
execute store result entity @e[type=fireball,tag=turretz_fireball,limit=1,sort=nearest] direction[0] double -0.01 run scoreboard players get @s x_pos
execute store result entity @e[type=fireball,tag=turretz_fireball,limit=1,sort=nearest] direction[1] double -0.01 run scoreboard players get @s y_pos
execute store result entity @e[type=fireball,tag=turretz_fireball,limit=1,sort=nearest] direction[2] double -0.01 run scoreboard players get @s z_pos
execute store result entity @e[type=fireball,tag=turretz_fireball,limit=1,sort=nearest] power[0] double -0.01 run scoreboard players get @s x_pos
execute store result entity @e[type=fireball,tag=turretz_fireball,limit=1,sort=nearest] power[1] double -0.01 run scoreboard players get @s y_pos
execute store result entity @e[type=fireball,tag=turretz_fireball,limit=1,sort=nearest] power[2] double -0.01 run scoreboard players get @s z_pos
scoreboard players reset @s x_pos
scoreboard players reset @s y_pos
scoreboard players reset @s z_pos
