#######
# Compiled from data/turretz/functions/arrow_turret.mcscript
# to .//data/turretz/functions/arrow_turret/aim.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s tur_turret_mode matches 1 run tp @s ~ ~ ~ facing entity @e[limit=1,sort=nearest,type=#unnamedde:hostile,distance=..20] eyes

execute if score @s tur_turret_mode matches 2 run tp @s ~ ~ ~ facing entity @e[limit=1,sort=nearest,type=!#unnamedde:non-living,type=!minecraft:player,distance=..20] eyes

execute if score @s tur_turret_mode matches 3 run tp @s ~ ~ ~ facing entity @e[limit=1,sort=nearest,type=!#unnamedde:non-living,distance=..20,gamemode=!creative,gamemode=!spectator] eyes

execute if score @s tur_turret_mode matches 4 run tp @s ~ ~ ~ facing entity @e[limit=1,sort=nearest,type=!#unnamedde:non-living,type=!#unnamedde:passive-neutral,distance=..20,gamemode=!creative,gamemode=!spectator] eyes

# /tp @s ~ ~ ~ facing entity @e[limit=1,sort=nearest,type=!#unnamedde:non-living,type=!minecraft:player,distance=..20] eyes
