#######
# Compiled from data/turretz/functions/arrow_turret.mcscript
# to .//data/turretz/functions/arrow_turret/place_auto.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function turretz:arrow_turret/place
kill @s[type=item]
