#######
# Compiled from data/turretz/functions/arrow_turret.mcscript
# to .//data/turretz/functions/arrow_turret/place_detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=item,nbt={Item:{tag:{turretz:{id:"skeleton_ai"}}}}] at @s unless entity @e[type=armor_stand,tag=turretz_turret,distance=..1.5] if block ~ ~-1 ~ #minecraft:wooden_fences if block ~ ~-2 ~ #minecraft:wooden_fences if block ~ ~-3 ~ minecraft:dispenser[facing=up] run function turretz:arrow_turret/place_auto
