#######
# Compiled from data/turretz/functions/arrow_turret.mcscript
# to .//data/turretz/functions/arrow_turret/shoot.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function turretz:arrow_turret/remove_arrow
scoreboard players set @s tur_cool 50
execute store result score @s x_pos run data get entity @s Pos[0] 100
execute store result score @s y_pos run data get entity @s Pos[1] 100
execute store result score @s z_pos run data get entity @s Pos[2] 100
summon area_effect_cloud ^ ^ ^2 {Tags:["turretz_dummy"]}
execute store result score @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] x_pos run data get entity @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] Pos[0] 100
execute store result score @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] y_pos run data get entity @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] Pos[1] 100
execute store result score @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] z_pos run data get entity @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] Pos[2] 100
scoreboard players operation @s x_pos -= @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] x_pos
scoreboard players operation @s y_pos -= @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] y_pos
scoreboard players operation @s z_pos -= @e[type=area_effect_cloud,tag=turretz_dummy,limit=1,sort=nearest] z_pos
summon arrow ^ ^ ^.5 {Tags:["turretz_arrow"],pickup:1b,Fire:-1s,player:1b,Color:-1}
execute store result entity @e[type=arrow,tag=turretz_arrow,limit=1,sort=nearest] Motion[0] double -0.01 run scoreboard players get @s x_pos
execute store result entity @e[type=arrow,tag=turretz_arrow,limit=1,sort=nearest] Motion[1] double -0.01 run scoreboard players get @s y_pos
execute store result entity @e[type=arrow,tag=turretz_arrow,limit=1,sort=nearest] Motion[2] double -0.01 run scoreboard players get @s z_pos
scoreboard players reset @s x_pos
scoreboard players reset @s y_pos
scoreboard players reset @s z_pos
