#######
# Compiled from data/turretz/functions/creative_menu.mcscript
# to .//data/turretz/functions/creative_menu/menu.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"text":"Turretz","color":"red"},{"text":" =====>","color":"aqua"}]
tellraw @s {"text":""}
#Content

#Wither Fragment
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s tur_c_menu 11"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s tur_c_menu 21"}},{"text":"] ","color":"reset"},{"text":"Wither Fragment"}]
#Skeleton AI
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s tur_c_menu 12"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s tur_c_menu 22"}},{"text":"] ","color":"reset"},{"text":"Skeleton AI"}]
#Ghast AI
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s tur_c_menu 13"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s tur_c_menu 23"}},{"text":"] ","color":"reset"},{"text":"Ghast AI"}]
#Wither AI
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s tur_c_menu 14"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s tur_c_menu 24"}},{"text":"] ","color":"reset"},{"text":"Wither AI"}]
tellraw @s {"text":""}
tellraw @s [{"text":" ↑ ","color":"red"},{"text":"Return to main menu","hoverEvent":{"action":"show_text","value":"Click to return"},"clickEvent":{"action":"run_command","value":"/function unnamedde:creative_menu"}}]
tellraw @s {"text":""}
tellraw @s {"text":""}
