#######
# Compiled from data/turretz/functions/creative_menu.mcscript
# to .//data/turretz/functions/creative_menu/select.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s [{"text":" ► ","color":"green"},{"text":"Turretz","hoverEvent":{"action":"show_text","value":"Click to select"},"clickEvent":{"action":"run_command","value":"/function turretz:creative_menu/menu"}}]
